environment:
  matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"

install:
      - cmd: choco install maven
      - cmd: refreshenv
      - cmd: cd C:\ProgramData\chocolatey\lib\maven\apache-maven-3.5.2\bin\
      - cmd: COPY mvn.cmd mvn.bat
      - cmd: COPY mvnDebug.cmd mvnDebug.bat
      - cmd: cd C:\projects\ci-maven

build_script:
      - "mvn clean install"

test: off
