environment:
  matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"

install:
    - cmd: |
        choco install maven
        refreshenv
        where mvn
        cd C:\projects\ci-common

before_build:
    - cmd: |
        echo "Installing ci.ant lib..."
        git clone -b devMode https://github.com/wasdev/ci.ant.git ci.ant
        cd ci.ant
        mvn clean install
        cd..

build_script:
      - "mvn clean install"

test: off
