environment:
  matrix:
        - jdk: "C:\\Program Files\\Java\\jdk1.8.0\\bin:"

install:
    - cmd: |
        choco install maven
        refreshenv
        where mvn
        cd C:\projects\ci-common

build_script:
      - "mvn clean install"

test: off
