/**
 * (C) Copyright IBM Corporation 2017, 2018.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.wasdev.wlp.common.arquillian.util;

public class Constants {

    public static final String CONFIGURE_ARQUILLIAN_COMMENT = "<!-- This file was generated by the Liberty build plugin. -->";
    
    public static final ArtifactCoordinates[] ARQUILLIAN_MANAGED_DEPENDENCY =
        {
            new ArtifactCoordinates("org.jboss.arquillian.container", "arquillian-wlp-managed-8.5"),
            new ArtifactCoordinates("io.openliberty.arquillian", "arquillian-liberty-managed") 
        };
    
    public static final ArtifactCoordinates[] ARQUILLIAN_REMOTE_DEPENDENCY = 
        {
            new ArtifactCoordinates("org.jboss.arquillian.container", "arquillian-wlp-remote-8.5"),
            new ArtifactCoordinates("io.openliberty.arquillian", "arquillian-liberty-remote") 
        };

}