package net.wasdev.wlp.common.arquillian.util;

public class Constants {

	public static final String CONFIGURE_ARQUILLIAN_COMMENT = "<!-- This file was generated by the Liberty build plugin. -->";
	
}
