package net.wasdev.wlp.common.arquillian.objects;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Map;
import java.util.Map.Entry;

import net.wasdev.wlp.common.arquillian.util.ArquillianProperty;

public class WLPManagedObject {

	private final String wlpHome;
	private final String serverName;
	private final int httpPort;
	private final Map<ArquillianProperty, String> arquillianProperties;

	public WLPManagedObject(String wlpHome, String serverName, int httpPort,
			Map<ArquillianProperty, String> arquillianProperties) {
		this.wlpHome = wlpHome;
		this.serverName = serverName;
		this.httpPort = httpPort;
		this.arquillianProperties = arquillianProperties;
	}

	public String getWlpHome() {
		return wlpHome;
	}

	public String getServerName() {
		return serverName;
	}

	public int getHttpPort() {
		return httpPort;
	}

	public Map<ArquillianProperty, String> getArquillianProperties() {
		return arquillianProperties;
	}

	public void build(File arquillianXml) throws IOException {
		// Generate the XML
		String xmlStart = 
				"<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n"
				+ "<arquillian xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
				+ "	xmlns=\"http://jboss.org/schema/arquillian\"\n"
				+ "	xsi:schemaLocation=\"http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd\">\n"
				+ "	<engine>\n"
				+ "		<property name=\"deploymentExportPath\">target/</property>\n"
				+ "	</engine>\n"
				+ "	<container qualifier=\"websphere\" default=\"true\">\n"
				+ "		<configuration>\n"
				+ "			<property name=\"wlpHome\">" + getWlpHome() + "</property>\n"
				+ "			<property name=\"serverName\">" + getServerName() + "</property>\n"
				+ "			<property name=\"httpPort\">" + getHttpPort() + "</property>\n";

		String xmlEnd = 
				"		</configuration>\n"
				+ "	</container>\n"
				+ "</arquillian>\n"
				+ "<!-- This file was generated by the Liberty build plugin. -->";

		String xmlProperties = "";
		for (Entry<ArquillianProperty, String> e : arquillianProperties.entrySet()) {
			String key = e.getKey().name();
			xmlProperties += "			<property name=\"" + key + "\">" + e.getValue() + "</property>\n";
		}

		// Write to file
		FileWriter writer = new FileWriter(arquillianXml);
		writer.write(xmlStart + xmlProperties + xmlEnd);
		writer.close();
	}

}
