package io.openliberty.tools.common.plugins.config;

import static org.junit.Assert.assertTrue;

import java.io.File;
import java.nio.file.Files;

import org.junit.Test;

public class ServerConfigXmlTest extends BaseConfigXmlTest {

    @Test
    public void createAppMonitorConfigTest() throws Exception {
        File serverDirectory = new File(serverConfigDir, "liberty/wlp/usr/servers/defaultServer");

        ApplicationMonitorConfigXmlDocument appMonXml = new ApplicationMonitorConfigXmlDocument("test");
        appMonXml.writeAppMonitorConfigXmlDocument(serverDirectory);

        File newFile = appMonXml.getAppMonitorConfigXmlFile(serverDirectory);
        String content = Files.readString(newFile.toPath());
        assertTrue(content.contains("Generated by liberty-test-plugin"));
        assertTrue(content.contains("<applicationMonitor updateTrigger=\"${io.openliberty.tools.update.trigger}\"/>"));
    }
}
