# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 8, 11, 17 ]

    steps:
    - name: Checkout ci.common
      uses: actions/checkout@v2
    - name: Checkout ci.ant
      uses: actions/checkout@v2
      with:
        repository: OpenLiberty/ci.ant
        path: ci.ant
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.1
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Install ci.ant
      run: |
        cd ./ci.ant
        mvn clean install
        cd ..
    - name: Build and run tests
      run: mvn clean install
