# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 8, 11 ]

    steps:
    - name: Setup Java ${{ matrix.java }}
      uses: joschi/setup-jdk@v2
      with:
        java-version: ${{ matrix.java }}
    - name: Checkout ci.common
      uses: actions/checkout@v2
    - name: Checkout ci.ant
      uses: actions/checkout@v2
      with:
        repository: OpenLiberty/ci.ant
        path: ci.ant
    - name: Cache maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install ci.ant
      run: |
        cd ./ci.ant
        mvn clean install
        cd ..
    - name: Build and run tests
      run: mvn clean install
