# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    strategy:
      fail-fast: false
      matrix:
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        os: [ ubuntu-latest, windows-latest ]
        java: [ 8, 11, 17, 21 ]

    steps:
    - name: Checkout ci.common
      uses: actions/checkout@v3
    - name: Checkout ci.ant
      uses: actions/checkout@v3
      with:
        repository: OpenLiberty/ci.ant
        path: ci.ant
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Install ci.ant
      run: |
        ./mvnw -V clean install -ntp -f ci.ant -DskipTests
    - name: Build and run tests
      run: ./mvnw -V clean install -ntp
